services:
  mongo:
    image: mongo:4.4.23
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: smart-assets
    ports:
      - 27017:27017
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
  service:
    image: smart-assets-be-challenge:latest
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATA_MONGODB_URI: mongodb://smart-assets:my-password@mongo:27017/smart-assets
      SPRING_DATA_MONGODB_DATABASE: smart-assets
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    depends_on:
      - mongo
    ports:
      - 8080:8080