spring:
  data:
    mongodb:
      uri: mongodb://smart-assets:my-password@localhost:27017/smart-assets
      database: smart-assets
  autoconfigure:
    exclude: de.flapdoodle.embed.mongo.spring.autoconfigure.EmbeddedMongoAutoConfiguration


